#!/bin/bash

function info {
	echo "[INFO] $1"
}

function warning {
	echo "[WARN] $1"
}

function error {
	echo "[ERROR] $1"
}

function dosomething {
	$1
	exc=$?
	if [ $exc -ne 0 ]; then
		error $2
		exit 2
	else
		if [ $3 ]; then
			error $2
			exit 2
		fi
	fi
}

function help {
	echo ,--------------------------------------,
	echo "|-------------REPO TOOL v1-------------|"
	echo "|-----------------HELP-----------------|"
	echo "'--------------------------------------'"
	echo
	echo ----------------------------------------
	echo "'"repo help"'" - Shows this help
	echo ----------------------------------------
	echo "'"repo fetch"'" - Fetches the code
	echo ----------------------------------------
	echo "'"repo sync"'" - Updates the repo
	echo ----------------------------------------
	echo "'"repo push"'" - Pushes Changes to the repositories
	echo ----------------------------------------
	echo
	echo
	exit 0
}

function folderlook {
	if [ -e $1 ]
	then
		info "$1 is present. Deleting Contents of folder."
		rm $1/*
	else
		info "$1 is not present... creating it!"
		mkdir $1
	fi
}



function remove {
	dosomething "rm -r $1" "Failed to rm $1" "-e $1"
}

function changedir {
	dosomething "cd $1" "Failed to cd to $1" "0 -ne 0"
}

function makedir {
	dosomething "mkdir $1" "Failed to mkdir $1" "! -e $1"
}

function move {
	dosomething "mv $1 $2" "Failed to mv $1 $2" "! -e $2"
}

function lookforfolder {
	if [ -e $1 ]; then
		info "Found folder $1"
	else
		makedir $1
	fi
}

function movemf {
	# MOVE More Files
	dosomething "mv $1 $2" "Failed to mv $1 $2" "0 -ne 0"
}

function gitpull {
	dosomething "git pull" "'Failed to git pull'" "! -e README.md"
}

function gitpush {
	dosomething "git push -u origin master" "'Failed to git push'" "! -e README.md"
}

function cdmvgitpull {
	changedir $1
	move gitfolder .git
	gitpull
	changedir ..
}

function cdgitpush {
	changedir $1
	dosomething "git add ." "Failed to git add!" "! -e README.md"
	dosomething "git commit -m '"add / modify some files"' " "Failed to git commit!" "! -e README.md"
	gitpush
	changedir ..
}

function firstFetch {
	info "Are the folders already present?"
	folderlook scripts/
	folderlook src/
	folderlook src/fw/
	folderlook src/fw/prog
	folderlook src/lib/
	folderlook src/lib/slip/
	folderlook src/software/

	info "Fetching Source-Code and install it..."
	git clone https://github.com/GymWenFLL/tpp_android_fetch_src
	git clone https://github.com/GymWenFLL/tpp_lib_src_insert
	git clone https://github.com/GymWenFLL/tpp_software_src_insert
	git clone https://github.com/GymWenFLL/tpp_fw_src_insert
	git clone https://github.com/GymWenFLL/tpp_helper_scripts_for_repo
	git clone https://github.com/GymWenFLL/tpp_automake_autoconf_files
	git clone https://github.com/GymWenFLL/tpp_scripts_to_install
	git clone https://github.com/GymWenFLL/tpp_lib_slip_src_insert

	mv tpp_scripts_to_install/* scripts/
	mv tpp_scripts_to_install/.git/ scripts/
	mv tpp_helper_scripts_for_repo/* ./
	mv tpp_fw_src_insert/* src/fw/prog/
	mv tpp_fw_src_insert/.git src/fw/prog/
	mv tpp_android_fetch_src/* src/fw/
	mv tpp_android_fetch_src/.git src/fw/
	mv tpp_lib_src_insert/* src/lib/
	mv tpp_lib_src_insert/.git src/lib/
	mv tpp_lib_slip_src_insert/* src/lib/slip/
	mv tpp_lib_slip_src_insert/.git src/lib/slip/
	mv tpp_software_src_insert/* src/software/
	mv tpp_software_src_insert/.git src/software/
	mv tpp_automake_autoconf_files/Makefile_scripts.am scripts/Makefile.am
	mv tpp_automake_autoconf_files/Makefile_src.am src/Makefile.am
	mv tpp_automake_autoconf_files/Makefile_src_fw.am src/fw/Makefile.am
	mv tpp_automake_autoconf_files/Makefile_src_lib src/lib/Makefile
	mv tpp_automake_autoconf_files/Makefile_src_lib_slip src/lib/slip/Makefile
	rm tpp_automake_autoconf_files/README.md
	mv tpp_automake_autoconf_files/* ./
	mv Makefile_top.am Makefile.am

	info "Install gitignores..."
	if [ -e src/fw/.gitignore ]; then
		info "Found src/fw/.gitignore"
	else
		echo prog/ >> src/fw/.gitignore
		echo "prog/ >> src/fw/.gitignore"
	fi

	echo scripts/ >> .gitignore
	echo src/ >> .gitignore
	echo aclocal.m4 >> .gitignore
	echo configure.ac >> .gitignore
	echo install.sh >> .gitignore
	echo Makefile.am >> .gitignore
	echo MakeOLD >> .gitignore
	echo update.sh >> .gitignore
	echo 'scripts/ >> .gitignore
		src/ >> .gitignore
		aclocal.m4 >> .gitignore
		configure.ac >> .gitignore
		install.sh >> .gitignore
		Makefile.am >> .gitignore
		MakeOLD >> .gitignore
		update.sh >> .gitignore'
	echo slip/ >> src/lib/.gitignore

	info "Work finished! cleaning up..."
	yes | rm -r tpp_android_fetch_src
	yes | rm -r tpp_automake_autoconf_files
	yes | rm -r tpp_fw_src_insert
	yes | rm -r tpp_helper_scripts_for_repo
	yes | rm -r tpp_lib_slip_src_insert
	yes | rm -r tpp_lib_src_insert
	yes | rm -r tpp_software_src_insert
	yes | rm -r tpp_scripts_to_install
	
	exit 0
}

function stashRepo {
	info "This Script will stash any changes you may have made."
	info "If you want to continue, you have to wait 5 seconds."

	timeout 5 ping localhost >/dev/null

	info "Cloning git-folder-tree and updating all repo's..."

	changedir ..
	dosomething "git clone https://github.com/GymWenFLL/tpp_gftree" "'Failed to pull the git-folder-tree, exiting...'" "! -e tpp_gftree"
	changedir tpp_gftree

	cdmvgitpull tpp_android_fetch_src
	cdmvgitpull tpp_automake_autoconf_files
	cdmvgitpull tpp_fw_src_insert
	cdmvgitpull tpp_helper_scripts_for_repo
	cdmvgitpull tpp_lib_slip_src_insert
	cdmvgitpull tpp_lib_src_insert
	cdmvgitpull tpp_repo
	cdmvgitpull tpp_scripts_to_install
	cdmvgitpull tpp_software_src_insert

	info "Wiping everything of the working-directory..."
	changedir ../tpp_repo
	remove scripts/
	remove src/
	remove aclocal.m4
	remove configure.ac
	remove install.sh
	remove LICENSE
	remove Makefile.am
	remove MakeOLD
	remove README
	remove update.sh

	changedir ..
	info "Looking for folders to fill... if not present create them."
	lookforfolder tpp_repo
	lookforfolder tpp_repo/src/lib/
	lookforfolder tpp_repo/src/lib/slip/
	lookforfolder tpp_repo/repoSh_experimental
	lookforfolder tpp_repo/scripts/
	lookforfolder tpp_repo/src/software/
	lookforfolder tpp_repo/src/fw/

	info "Paste the repo files into the working-directory..."
	movemf tpp_gftree/tpp_android_fetch_src/* tpp_repo/src/fw/
	movemf tpp_gftree/tpp_automake_autoconf_files/* tpp_repo/
	movemf tpp_gftree/tpp_fw_src_insert/* tpp_repo/src/fw/
	movemf tpp_gftree/tpp_helper_scripts_for_repo/ tpp_repo/repoSh_experimental
	movemf tpp_gftree/tpp_lib_slip_src_insert/* tpp_repo/lib/slip/
	movemf tpp_gftree/tpp_lib_src_insert/* tpp_repo/src/lib/
	movemf tpp_gftree/tpp_scripts_to_install/* tpp_repo/scripts/
	movemf tpp_gftree/tpp_software_src_insert/* tpp_repo/src/software/

	changedir tpp_repo
	move Makefile_scripts.am scripts/Makefile.am
	move Makefile_src.am src/Makefile.am
	move Makefile_src_fw.am src/fw/Makefile.am
	move Makefile_src_lib src/lib/Makefile
	move Makefile_src_lib_slip src/lib/slip/Makefile

	changedir ..

	info "Cleaning Up..."
	remove tpp_gftree

	info "Finished!"
	exit 0
}

function pushRepo {
	info "Push changes to the Repositories..."
	
	changedir ..
	info "Pull the git-folder-tree..."
	dosomething "git clone https://github.com/GymWenFLL/tpp_gftree" "'Failed to pull the git-folder-tree, exiting...'" "-e tpp_gftree"
	changedir tpp_gftree
	
	info "making it usable..."
	cdmvgitpull tpp_android_fetch_src
	cdmvgitpull tpp_automake_autoconf_files
	cdmvgitpull tpp_fw_src_insert
	cdmvgitpull tpp_helper_scripts_for_repo
	cdmvgitpull tpp_lib_slip_src_insert
	cdmvgitpull tpp_lib_src_insert
	cdmvgitpull tpp_repo
	cdmvgitpull tpp_scripts_to_install
	cdmvgitpull tpp_software_src_insert
	
	changedir ..
	
	info "copying files to the repositories..."
	
	info "tpp_android_fetch_src"
	move tpp_repo/src/fw/scripts tpp_gftree/tpp_android_fetch_src/
	
	info "tpp_automake_autoconf_files"
	move tpp_repo/Makefile.am tpp_gftree/tpp_automake_autoconf_files/
	move tpp_repo/aclocal.m4 tpp_gftree/tpp_automake_autoconf_files/
	move tpp_repo/scripts/Makefile.am tpp_gftree/tpp_automake_autoconf_files/Makefile_scripts.am
	move tpp_repo/src/Makefile.am tpp_gftree/tpp_automake_autoconf_files/Makefile_src.am
	move tpp_repo/src/fw/Makefile.am tpp_gftree/tpp_automake_autoconf_files/Makefile_src_fw.am
	move tpp_repo/src/lib/Makefile tpp_gftree/tpp_automake_autoconf_files/Makefile_src_lib
	move tpp_repo/src/lib/slip/Makefile tpp_gftree/tpp_automake_autoconf_files/Makefile_src_lib_slip
	move tpp_repo/configure.ac tpp_gftree/tpp_automake_autoconf_files/
	
	info "tpp_fw_src_insert"
	move tpp_repo/src/fw/code/ tpp_gftree/tpp_fw_src_insert/
	move tpp_repo/src/fw/conn.sh tpp_gftree/tpp_fw_src_insert/
	
	info "tpp_helper_scripts_for_repo"
	movemf tpp_repo/repoSh_experimental/* tpp_gftree/tpp_helper_scripts_for_repo/
	
	info "tpp_lib_slip_src_insert"
	movemf tpp_repo/lib/slip/* tpp_gftree/tpp_lib_slip_src_insert/
	
	info "tpp_lib_src_insert"
	move tpp_repo/src/lib/stdlib/ tpp_gftree/tpp_lib_src_insert/
	
	info "tpp_scripts_to_install"
	movemf tpp_repo/scripts/* tpp_gftree/tpp_scripts_to_install/
	
	info "tpp_software_src_insert"
	movemf tpp_gftree/tpp_software_src_insert/* tpp_repo/src/software/
	
	changedir tpp_gftree
	
	info "pushing code to master..."
	cdgitpush tpp_android_fetch_src
	cdgitpush tpp_automake_autoconf_files
	cdgitpush tpp_fw_src_insert
	cdgitpush tpp_helper_scripts_for_repo
	cdgitpush tpp_lib_slip_src_insert
	cdgitpush tpp_lib_src_insert
	cdgitpush tpp_repo
	cdgitpush tpp_scripts_to_install
	cdgitpush tpp_software_src_insert
}

if [ ! $1 ]; then
	help
fi

if [ $1 = "help" ]; then
	help
fi

if [ $1 = "fetch" ]; then
	firstFetch
fi

if [ $1 = "stash" ]; then
	stashRepo
fi

if [ $1 = "push" ]; then
	error "Unimplemented!"
	exit 1
fi

error "Wrong (spelled) or unimplemented command... maybe try with help?"
help

