#!/bin/bash

function info {
	echo "[INFO] $1"
}

function warning {
	echo "[WARN] $1"
}

function error {
	echo "[ERROR] $1"
}

function dosomething {
	$1
	exc=$?
	if [ $exc -ne 0 ]; then
		error $2
		exit 2
	else
		if [ $3 ]; then
			error $2
			exit 2
		fi
	fi
}

function help {
	echo ,--------------------------------------,
	echo "|-----------REPO TOOL v1.0a------------|"
	echo "|-----------------HELP-----------------|"
	echo "'--------------------------------------'"
	echo
	echo ----------------------------------------
	echo "'"repo help"'" - Shows this help
	echo ----------------------------------------
	echo "'"repo fetch"'" - Fetches the code
	echo ----------------------------------------
	echo "'"repo sync"'" - Updates the repo
	echo ----------------------------------------
	echo "'"repo push"'" - Pushes Changes to the repositories
	echo ----------------------------------------
	echo
	echo
	exit 0
}

function folderlook {
	if [ -e $1 ]
	then
		info "$1 is present. Deleting Contents of folder."
		rm $1/*
	else
		info "$1 is not present... creating it!"
		mkdir $1
	fi
}



function remove {
	dosomething "rm -r $1" "Failed to rm $1" "-e $1"
}

function changedir {
	dosomething "cd $1" "Failed to cd to $1" "0 -ne 0"
}

function makedir {
	dosomething "mkdir $1" "Failed to mkdir $1" "! -e $1"
}

function move {
	dosomething "mv $1 $2" "Failed to mv $1 $2" "! -e $2"
}

function lookforfolder {
	if [ -e $1 ]; then
		info "Found folder $1"
	else
		makedir $1
	fi
}

function movemf {
	# MOVE More Files
	dosomething "mv $1 $2" "Failed to mv $1 $2" "0 -ne 0"
}

function gitpull {
	dosomething "git pull" "'Failed to git pull'" "! -e README.md"
}

function gitpush {
	dosomething "git push -u origin master" "'Failed to git push'" "! -e README.md"
}

function cdmvgitpull {
	changedir $1
	move gitfolder .git
	gitpull
	changedir ..
}

function cdgitpush {
	changedir $1
	dosomething "git add ." "Failed to git add!" "! -e README.md"
    read -p "What have you done since the last commit? (This will be the commit message) " cmsg
	dosomething "git commit -m '"$cmsg"' " "Failed to git commit!" "! -e README.md"
	gitpush
	changedir ..
}

function firstFetch {
	info "Are the folders already present?"
	folderlook scripts/
	folderlook src/
	folderlook src/fw/
	folderlook src/fw/prog
	folderlook src/lib/
	folderlook src/lib/slip/
	folderlook src/software/

	info "Fetching Source-Code and install it..."
	git clone https://github.com/GymWenFLL/tpp_android_fetch
	git clone https://github.com/GymWenFLL/tpp_lib_src
	git clone https://github.com/GymWenFLL/tpp_software_src
	git clone https://github.com/GymWenFLL/tpp_fw_src
	git clone https://github.com/GymWenFLL/tpp_autotool
	git clone https://github.com/GymWenFLL/tpp_installedscripts
	git clone https://github.com/GymWenFLL/tpp_lib_slip_src
    #git clone https://github.com/GymWenFLL/tpp_lib_stdlib

	mv tpp_installedscripts/conn.sh scripts/
	mv tpp_installedscripts/Makefile scripts/
	mv tpp_fw_src/* src/fw/prog/
	mv tpp_android_fetch/* src/fw/
	mv tpp_lib_src/* src/lib/
	mv tpp_lib_slip_src/* src/lib/slip/
	mv tpp_software_src/* src/software/
	mv tpp_automake_autoconf_files/aclocal.m4 ./aclocal.m4
    
	info "Work finished! cleaning up..."
	yes | rm -r tpp_android_fetch_src
	yes | rm -r tpp_automake_autoconf_files
	yes | rm -r tpp_fw_src_insert
	yes | rm -r tpp_helper_scripts_for_repo
	yes | rm -r tpp_lib_slip_src_insert
	yes | rm -r tpp_lib_src_insert
	yes | rm -r tpp_software_src_insert
	yes | rm -r tpp_scripts_to_install
	
	exit 0
}

function updateRepo {
	info "This Script will update any changes you may have made."
	info "If you want to continue, you have to wait 5 seconds."

	timeout 5 ping localhost >/dev/null

	info "Cloning git-folder-tree and updating all repo's..."

	changedir ..
	dosomething "git clone https://github.com/GymWenFLL/tpp_gftree" "'Failed to pull the git-folder-tree, exiting...'" "! -e tpp_gftree"
	changedir tpp_gftree

	cdmvgitpull tpp_android_fetch
	cdmvgitpull tpp_autotool
	cdmvgitpull tpp_fw_src
	cdmvgitpull tpp_lib_slip_src
	cdmvgitpull tpp_lib_src
	cdmvgitpull tpp_repo
	cdmvgitpull tpp_installedscripts
	cdmvgitpull tpp_software_src

	info "Looking for folders to fill... if not present create them."
	lookforfolder tpp_repo
	lookforfolder tpp_repo/src/lib/
	lookforfolder tpp_repo/src/lib/slip/
	lookforfolder tpp_repo/repoSh_experimental
	lookforfolder tpp_repo/scripts/
	lookforfolder tpp_repo/src/software/
	lookforfolder tpp_repo/src/fw/

	info "Paste the repo files into the working-directory..."
	movemf tpp_gftree/tpp_android_fetch/* tpp_repo/src/fw/
	movemf tpp_gftree/tpp_fw_src/* tpp_repo/src/fw/
	movemf tpp_gftree/tpp_lib_slip_src/* tpp_repo/lib/slip/
	movemf tpp_gftree/tpp_lib_src/* tpp_repo/src/lib/
	movemf tpp_gftree/tpp_installedscripts/* tpp_repo/scripts/
	movemf tpp_gftree/tpp_software_src/* tpp_repo/src/software/

	info "Cleaning Up..."
	remove tpp_gftree

	info "Finished!"
	exit 0
}

function stashRepo {
	echo Wiping every change you may have made and refetch the codebase.
    echo Wiping everything...
    yes | rm -r scripts/
    yes | rm -r src/
    yes | rm aclocal.m4
    yes | rm configure
    yes | rm Makefile
    firstFetch
}

function pushRepo {
	info "Push changes to the Repositories..."
	
	changedir ..
	info "Pull the git-folder-tree..."
	dosomething "git clone https://github.com/GymWenFLL/tpp_gftree" "'Failed to pull the git-folder-tree, exiting...'" "-e tpp_gftree"
	changedir tpp_gftree
	
	info "making it usable..."
	cdmvgitpull tpp_android_fetch
	cdmvgitpull tpp_autotool
	cdmvgitpull tpp_fw_src
	cdmvgitpull tpp_lib_slip_src
	cdmvgitpull tpp_lib_src
	cdmvgitpull tpp_repo
	cdmvgitpull tpp_installedscripts
	cdmvgitpull tpp_software_src
	
	changedir ..
	
	info "copying files to the repositories..."
	
	info "tpp_android_fetch"
	move tpp_repo/src/fw/scripts tpp_gftree/tpp_android_fetch/
	
	info "tpp_fw_src"
	move tpp_repo/src/fw/code/ tpp_gftree/tpp_fw_src/
	move tpp_repo/src/fw/conn.sh tpp_gftree/tpp_fw_src/
	
	info "tpp_lib_slip_src"
	movemf tpp_repo/lib/slip/* tpp_gftree/tpp_lib_slip_src/
	
	info "tpp_lib_src"
	move tpp_repo/src/lib/stdlib/ tpp_gftree/tpp_lib_src/
	
	info "tpp_installedscripts"
	movemf tpp_repo/scripts/* tpp_gftree/tpp_scripts_to_install/
	
	info "tpp_software_src_insert"
	movemf tpp_gftree/tpp_software_src_insert/* tpp_repo/src/software/
	
	changedir tpp_gftree
	
	info "pushing code to master..."
	cdgitpush tpp_android_fetch
	cdgitpush tpp_autotool
	cdgitpush tpp_fw_src
	cdgitpush tpp_lib_slip_src
	cdgitpush tpp_lib_src
	cdgitpush tpp_repo
	cdgitpush tpp_installedscripts
	cdgitpush tpp_software_src
}

if [ ! $1 ]; then
	help
fi

if [ $1 = "help" ]; then
	help
fi

if [ $1 = "fetch" ]; then
	firstFetch
fi

if [ $1 = "stash" ]; then
	stashRepo
fi

if [ $1 = "push" ]; then
	error "Unimplemented!"
	exit 1
fi

error "Wrong (spelled) or unimplemented command... maybe try with help?"
help