#!/bin/bash

function info {
	echo "[INFO] $1"
}

function warn {
	echo "[WARN] $1"
}

function error {
	echo "[ERROR] $1"
}

function execute {
	$1
	exc=$?
	if [ $exc -ne 0 ]; then
		error $2
		exit 2
	else
	if [ $3 ]; then
		error $2
		exit 2
	fi
}

folderfail="Failed to cd to "
mvfail="Failed to mv "
gitfail="Failed to git pull"
rmfail="Failed to rm "
mkfolderfail="Failed to mkdir "

function remove {
	execute "rm -r $1" "$rmfail $1" "-e $1"
}

function changedir {
	execute "cd $1" "$folderfail $1" "0 -ne 0"
}

function makedir {
	execute "mkdir $1" "$mkfolderfail $1" "! -e $1"
}

function move {
	execute "mv $1 $2" "$mvfail $1 $2" "! -e $2"
}

function lookforfolder {
	if [ -e $1 ]; then
		info "Found folder $1"
	else
		makedir $1
	fi
}

function movemf {
	# MOVE More Files
	execute "mv $1 $2" "$mvfail $1 $2" "0 -ne 0"
}

function gitpull {
	execute "git pull" "'$gitfail'" "! -e README.md"
}

function cdmvgitpull {
	changedir $1
	move gitfolder .git
	gitpull
}

info "This Script will stash any changes you may have made."
info "If you want to continue, you have to wait 5 seconds."

timeout 5 ping localhost >/dev/null

info "Cloning git-folder-tree and updating all repo's..."

changedir ..
execute "git clone https://github.com/GymWenFLL/tpp_gftree" "'Failed to pull the git-folder-tree, exiting...'" "-e tpp_gftree"
changedir tpp_gftree

cdmvgitpull tpp_android_fetch_src
cdmvgitpull tpp_automake_autoconf_files
cdmvgitpull tpp_fw_src_insert
cdmvgitpull tpp_helper_scripts_for_repo
cdmvgitpull tpp_lib_slip_src_insert
cdmvgitpull tpp_lib_src_insert
cdmvgitpull tpp_repo
cdmvgitpull tpp_scripts_to_install
cdmvgitpull tpp_software_src_insert

info "Wiping everything of the working-directory..."
changedir ../tpp_repo
remove scripts/
remove src/
remove aclocal.m4
remove configure.ac
remove install.sh
remove LICENSE
remove Makefile.am
remove MakeOLD
remove README
remove repo
remove update.sh

changedir ..
info "Looking for folders to fill... if not present create them."
lookforfolder tpp_repo
lookforfolder tpp_repo/src/lib/
lookforfolder tpp_repo/src/lib/slip/
lookforfolder tpp_repo/repoSh_experimental
lookforfolder tpp_repo/scripts/
lookforfolder tpp_repo/src/software/
lookforfolder tpp_repo/src/fw/

info "Paste the repo files into the working-directory..."
movemf tpp_gftree/tpp_android_fetch_src/* tpp_repo/src/fw/
movemf tpp_gftree/tpp_automake_autoconf_files/* tpp_repo/
move tpp_gftree/tpp_fw_src_insert/conn.sh tpp_repo/src/fw/
movemf tpp_gftree/tpp_helper_scripts_for_repo/ tpp_repo/repoSh_experimental
movemf tpp_gftree/tpp_lib_slip_src_insert/* tpp_repo/lib/slip/
movemf tpp_gftree/tpp_lib_src_insert/* tpp_repo/src/lib/
move tpp_gftree/tpp_repo/repo tpp_repo/
movemf tpp_gftree/tpp_scripts_to_install/* tpp_repo/scripts/
movemf tpp_gftree/tpp_software_src_insert/* tpp_repo/src/software/

changedir tpp_repo
move Makefile_scripts.am scripts/Makefile.am
move Makefile_src.am src/Makefile.am
move Makefile_src_fw.am src/fw/Makefile.am
move Makefile_src_lib src/lib/Makefile
move Makefile_src_lib_slip src/lib/slip/Makefile

changedir ..

info "Cleaning Up..."
remove tpp_gftree

info "Finished!"
exit 0